### ISSUE TITLE
Does not work with Portable Visual Studio Code

### ISSUE THREAD

**Issue by jwstevensii** [shanalikhan/code-settings-sync#331]
**Visual Studio Code Version :** 1.12.2
**Code Settings Sync Version :** 2.8.0
**Operating System :** Windows 10.0.14393
**Occurs On:** Upload / Download
**Proxy Enabled:** No
**GIst Id:** jwstevensii

Sync does not properly work when Launching Visual Studio Code with the below parameters 

**--user-data-dir**=[Alternate folder here]
**--extensionHomePath**=[Alternate folder here]

**Comment by shanalikhan** [comment]
It doesnt support portable vs code now. We will see what can be done later on.

**Comment by shanalikhan** [comment]
Pending for 
https://github.com/Microsoft/vscode/issues/2741

**Comment by tqhao94** [comment]
Hi, any news for portable vscode ?

**Comment by GandalfSaxe** [comment]
@shanalikhan As far as I can see, you're pending for Microsoft/vscode#2741 because you want to support the portable version in a safe manner instead of hard cording paths. This is reasonable, but how about just starting portable version support by hard coding? It may be a bit of maintenance, but it really sucks to manually copy paste settings across files right now. Besides, I can't see any reason it's worse with the portable version as the regular version? Both must be hard coded now?

There are slight differences, e.g. Windows uses `data` in the same folder level as `Code.exe` whereas macOS uses `code-portable-data` at the same level as `Visual Studio Code.app`. But surely this is identical to treating different OSs for the non-portable VSCode?

Btw I wouldn't mind maintaining any changes made to the portable paths at least for the macOS version until we hopefully get these at an API level.

**Comment by shanalikhan** [comment]
Yes you are right.
I am currently checking if visual studio code provide some sort of flag that shows user is running a portable mode than hard code path can be used for now.
But if they dont even provide some method to check the portable mode is running or standard then i have to dig into a longer route by viewing  the standard paths for code variants ( standard, insiders ) for each OS ( windows, Mac, Ubuntu ) and then setting hard code path as above for portable mode

**Comment by GandalfSaxe** [comment]
Gotcha.

You could just introduce a "sync.isUsingPortable" setting that defaults to `false` for now. If set to `true`, then it use a different set of paths.

Let me know if I can be of any help. I use both Windows and macOS at the moment.

**Comment by shanalikhan** [comment]
Yes, if there will no other option then I would have to go manual setup to adding keys.

**Comment by GandalfSaxe** [comment]
I can't help but to notice that the issue in question has been open since February 2016, so I'd say we shouldn't hold our breath for that one. Better to have a less elegant, but working solution now.

As I said, let me know if I can help in any way.

**Comment by shanalikhan** [comment]
> As I said, let me know if I can help in any way.

If you can help - It would be great If you can just PR fixing this - Will be released with v3.1

Let me know if you are willing, we can discuss it.

References:
https://github.com/Microsoft/vscode/issues/49306
vsicons PR for adding portable  - https://github.com/vscode-icons/vscode-icons/pull/1651

**Comment by GandalfSaxe** [comment]
Hmm may be a little over my head compared with the time I have at the moment. Sorry.

**Comment by mpearon** [comment]
Hey, @shanalikhan!  Just checking in - is a temporary solution still on the radar?
Great work with Settings Sync. Not sure how the world survived without it.

**Comment by CyrilTaylor** [comment]
[not work with Settings Sync(shan.code-settings-sync)](https://github.com/myfreeer/vscode-portable/issues/1)

That's because the extension does not honor VSCODE_APPDATA environment variable, just ask them to implement support.

Check src/paths.js of vscode and src/environmentPath.ts of code-settings-sync for more details.

**Comment by shanalikhan** [comment]
I have created a PR to support portable mode.
But it will only support the default portable mode directory structure mentioned by Visual Studio Code Team.

![image](https://user-images.githubusercontent.com/8774556/46795860-9c72e800-cd64-11e8-8390-7c856550da23.png)


I dont have Mac so at the moment, Settings Sync wont support Portable Mode over Mac.

Will be released in a week.

**Comment by shanalikhan** [comment]
v3.2 is released with this feature. Let me know if there is any problem

**Comment by GandalfSaxe** [comment]
How is it closed if it doesn’t work on Mac? Do you want a separate issue for that?

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/684

PR is welcome for Mac.

**Comment by Ash258** [comment]
Still seeing error using 3.2.0

```javascript
[Extension Host] TypeError: Cannot read property 'token' of undefined
	at Commons.<anonymous> (C:\Scoop\persist\vscode-insiders\data\extensions\shan.code-settings-sync-3.2.0\out\src\commons.js:216:29)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Scoop\persist\vscode-insiders\data\extensions\shan.code-settings-sync-3.2.0\out\src\commons.js:4:58)
	at <anonymous> (at Function.LogException (C:\Scoop\persist\vscode-insiders\data\extensions\shan.code-settings-sync-3.2.0\out\src\commons.js:28:21))
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:437
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180

notificationsAlerts.ts:40 Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
t.onDidNotificationChange | @ | notificationsAlerts.ts:40
-- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | e.fire | @ | event.ts:145
  | t.notify | @ | notifications.ts:113
  | t.notify | @ | notificationService.ts:52
  | e._showMessage | @ | mainThreadMessageService.ts:83
  | e._showMessage | @ | mainThreadMessageService.ts:44
  | e.$showMessage | @ | mainThreadMessageService.ts:38
  | t._doInvokeHandler | @ | rpcProtocol.ts:439
  | t._invokeHandler | @ | rpcProtocol.ts:424
  | t._receiveRequest | @ | rpcProtocol.ts:341
  | t._receiveOneMessage | @ | rpcProtocol.ts:271
  | (anonymous) | @ | rpcProtocol.ts:146
  | e.fire | @ | event.ts:145
  | a | @ | ipc.net.ts:103
  | n._socketDataListener | @ | ipc.net.ts:132
  | emitOne | @ | events.js:116
  | emit | @ | events.js:211
  | addChunk | @ | _stream_readable.js:263
  | readableAddChunk | @ | _stream_readable.js:250
  | Readable.push | @ | _stream_readable.js:208
  | onread | @ | net.js:594

```

- Version: 1.29.0-insider
- Commit: 799bc78af597769a5dd5a6b002359ddae412b1be
- Date: 2018-10-17T05:19:06.776Z
- Electron: 2.0.11
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64

**Comment by OrangeDrangon** [comment]
I fixed this error by creating a sync.lock than installing the extension. Now it is not picking up on my extensions in the portable install though.

**Comment by neapolis79** [comment]
same issue on my new laptop.
When upload settings i see extension added, but in the new pc i read "No extensions installed"

**Comment by amal-khailtash** [comment]
Same problem and error on Windows 10 and VSCode:
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by tmeckel** [comment]
Still doesn't work when `--user-data-dir=` ref to my comment at https://github.com/Microsoft/vscode/issues/49306

**Comment by shanalikhan** [comment]
Settings Sync now supports portable mode in Mac
v2.3.4 Released.

**Comment by shanalikhan** [comment]
Yes, try with auto upload / download turned off. Create new issue if there is any problem.

**Comment by GandalfSaxe** [comment]
@shanalikhan Awesome! 🎉 I haven't tested it thoroughly yet, but I've tried it out a little, and it seems to work. Thanks!

**Comment by strange-life** [comment]
@shanalikhan I installed vscode-portable with scoop and couldn't synchronize the complete extension list
![image](https://user-images.githubusercontent.com/19758341/50482958-5c96d500-0a24-11e9-9bfd-825e6166c94b.png)
![image](https://user-images.githubusercontent.com/19758341/50482965-66b8d380-0a24-11e9-89f9-b5a7cf33961d.png)
Version: 1.30.1
If you are free, please help me to look at this problem. Thank you very much.

**Comment by babyadoresorange** [comment]
@shanalikhan 
Hello, I'm on vscode 1.33.1 portable.
Uploading is fine but I cannot download extensions, only settings files are downloaded.
There is no error throw, juts 0 extension added.

I also try upload then force download and got the same thing.

Can you look into this ?

**Comment by shanalikhan** [comment]
@babyadoresorange please open new ticket with the details reproducing steps.
