### ISSUE TITLE
[bug] open browser when setting is locked

### ISSUE THREAD

**Issue by Cologler** [shanalikhan/code-settings-sync#363]
**Code Settings Sync Version :**  2.8.2

When I open vscode second instance, it show error message and open url `http://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html`:

``` log
Lock is not acquired/owned by you: Error: Lock is not acquired/owned by you
    at canonicalPath (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\index.js:254:43)
    at Object.realpath (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\lib\syncFs.js:17:9)
    at canonicalPath (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\index.js:21:16)
    at unlock (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\index.js:245:5)
    at Function.unlockSync (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\index.js:302:5)
    at Commons.<anonymous> (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\out\src\commons.js:69:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\out\src\commons.js:4:58)
```

expected:

do not open url if the file is locked.

**Comment by shanalikhan** [comment]
> When I open vscode second instance

Can you write down all the steps from start so i can reproduce it at my end.

Thanks

**Comment by Cologler** [comment]
1. Open vscode on folder.
2. Open vscode on another folder immediately.

The first vscode popup a message `Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON.`, and show those message in developer tool:

```
[Extension Host] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Commons.<anonymous> (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\out\src\commons.js:223:44)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\out\src\commons.js:4:58)

Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON.
```

The second vscode show those message in developer tool:

```
Lock is not acquired/owned by you: Error: Lock is not acquired/owned by you
    at canonicalPath (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\index.js:254:43)
    at Object.realpath (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\lib\syncFs.js:17:9)
    at canonicalPath (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\index.js:21:16)
    at unlock (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\index.js:245:5)
    at Function.unlockSync (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\node_modules\proper-lockfile\index.js:302:5)
    at Commons.<anonymous> (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\out\src\commons.js:69:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\skyof\.vscode\extensions\Shan.code-settings-sync-2.8.2\out\src\commons.js:4:58)
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
```

**Comment by Cologler** [comment]
This is not one hundred percent happen.

**Comment by Cologler** [comment]
Is possible the vscode 2 writing `syncLocalSettings.json` and vscode 1 reading it ?

**Comment by Cologler** [comment]
This pr had not fixed the lock problem. (⊙﹏⊙)

**Comment by shanalikhan** [comment]
Thanks for the PR, i will accept it, also will reproduce the error and get back to you in few days.

**Comment by Cologler** [comment]
Oh, this issus is occur when I set the option: `"sync.autoUpload": true`

**Comment by wsmelton** [comment]
It is quite annoying to constantly have the web browser open just because it can't sync. Is there anyway to disable that so it stops doing it?

I commonly work with more than one window of Code and understand that will prevent the sync from working properly.

**Comment by shanalikhan** [comment]
@Cologler i have released your PR in the 2.8.3 version.
Seems like its fixed as i was not able to product using these steps : https://github.com/shanalikhan/code-settings-sync/issues/363#issuecomment-316020364

@wsmelton update and let me know. Or write the steps in detail so i can reproduce at my end.

**Comment by Cologler** [comment]
@shanalikhan This is a temporary solution and it cannot fix other cross process issues.

**Comment by shanalikhan** [comment]
Yes i know, i need to have step to reproduce at my end in order to fix it.

**Comment by shanalikhan** [comment]
I'm closing this issue as there are no concrete steps to reproduce also since last year. Extension code is refactored and improved.
Feel free to create a new issue with the detailed steps if there is any in the current version.

**Comment by gnomeria** [comment]
Btw this is still happening with version 3.2.8. I'll investigate later

**Comment by QueenKunkun** [comment]
![image](https://user-images.githubusercontent.com/31095123/142713421-0fe3924c-e42d-4827-8643-f1c38664cf96.png)
It should be caused by a legacy setting file which was failed to load by the extension. see the above screenshot, left is the legacy file and right is the new file.

so the solution should be either fix the setting file or delete it and let it be generated again.
