### ISSUE TITLE
Doesn't work on Linux Mint 18.2, shift+alt+u doesn't work.

### ISSUE THREAD

**Issue by WuShichao** [shanalikhan/code-settings-sync#383]
**Visual Studio Code Version :** [ 1.15.1 ]
**Code Settings Sync Version :** [ 2.8.2 ]
**Operating System :** [ Linux Mint 18.2 sonya 64bits ]
**Occurs On:** [ Configuring ]
**Proxy Enabled:** [ Yes ]
**GIst Id:** [ 4174df0c088605e770e07402180750a7e909c0c2 ]

![image](https://user-images.githubusercontent.com/6574526/29443474-d8a90e2a-840a-11e7-92fd-49d43dbbd47c.png)

**Comment by sayanriju** [comment]
Similar problem in Kubuntu 16.04 as well.
VS Code version: 1.15.1

**Comment by shanalikhan** [comment]
what is the exception logged, in the developer console

**Comment by kemelzaidan** [comment]
Doesn't work on Ubuntu 17.04. Didn't see any output on the developer console. It simply doesn't work?

**Comment by kemelzaidan** [comment]
It is the same bug as #327. The workaround in there, fixes the problem.

**Comment by WuShichao** [comment]
@shanalikhan Didn't see any output on the developer console. It simply doesn't work.

**Comment by shanalikhan** [comment]
#327 is fixed
@WuShichao can you update the extension and clear all the extension settings and let me know.

**Comment by WuShichao** [comment]
@shanalikhan Thx~Now I can upload, but when I download, I just get the errors below
![2017-08-20 21-44-27](https://user-images.githubusercontent.com/6574526/29496246-69542cd2-8601-11e7-880d-7857cdfe022f.png)
![2017-08-20 21-55-22](https://user-images.githubusercontent.com/6574526/29496249-6cdb3ef4-8601-11e7-9e25-52c4fcd63430.png)
Can't sync, and the "shift+alt+u/d" still doesn't work, but I can type ">Sync" and select them by using mouse.

**Comment by WuShichao** [comment]
@shanalikhan Thx~
![2017-08-21 09-48-05](https://user-images.githubusercontent.com/6574526/29500813-672a34d8-8656-11e7-8a5a-14ebb5dbe197.png)

**Comment by shanalikhan** [comment]
@WuShichao when you set the sync settings inside `settings.json`.
make sure you **Close** settings.json file from editor.
Download again
and then post again this image
