### ISSUE TITLE
Extension host killed

### ISSUE THREAD

**Issue by wescoder** [shanalikhan/code-settings-sync#827]
🐛 **Describe the bug**  
After the last update of VSCode (1.33.0), `code-settings-sync` is killing the Extension Host.

🌴 **Visual Studio Code Version :** 1.33.0 
🌴 **Code Settings Sync Version :** 3.2.8 
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** Neither 
🌴 **Operating System :** MacOS Mojave 
🌴 **Occurs On:** Startup
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** 8a8afe3f5b1388e1ee949020690bd2f9

📰 **To Reproduce**
Start VSCode.

💪 **Expected behavior**
Extension should sync normally.

📺 **Console Error Log** 
Log from VSCode's DevTools:
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/wescoder/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/wescoder/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace


extensionService.ts:450 Extension host terminated unexpectedly. Code:  null  Signal:  SIGKILL
_onExtensionHostCrashed @ extensionService.ts:450
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
```
 
> Let me know how else can I help with this.

**Comment by shanalikhan** [comment]
>  code-settings-sync is killing the Extension Host.

can you post the image screen shot ? How you know Settings-Sync is killing host ?

**Comment by wescoder** [comment]
I've disabled all extensions, so the error got away, and enabled one by one and restarted between each until the error showed up again, and Sync was who caused it. Later today I'll post a screenshot.

**Comment by wescoder** [comment]
![image](https://user-images.githubusercontent.com/22945955/55633211-3c4c8400-5792-11e9-9013-34adda3f474d.png)
Here it is, I've disabled all other extensions.

VSCode version:
![image](https://user-images.githubusercontent.com/22945955/55633279-61d98d80-5792-11e9-802c-61eadd55c799.png)

Sync version:
![image](https://user-images.githubusercontent.com/22945955/55633342-87669700-5792-11e9-8313-92325ab723b2.png)

**Comment by shanalikhan** [comment]
@arnohovhannisyan

I think same issue happened previously due to which `chokidar` was removed from Settings Sync.
Can you look into this ?

Reference : 
https://github.com/shanalikhan/code-settings-sync/issues/762
https://github.com/Microsoft/vscode/issues/68024#issuecomment-461379608

**Comment by wescoder** [comment]
I've run `npm un -g fs-extra fs-events` and didn't help.
Is there any other steps related to #762 that you would recommend to do?
I'll be watching [Microsoft/vscode#68024](https://github.com/Microsoft/vscode/issues/68024) for any updates too.

Thanks for the support so far :)

**Comment by arnohovhannisyan** [comment]
I'm currently running v3.2.8 on macOS High Sierra with VS Code v1.33.0, but I'm not seeing any problems, and everything's working for me.

**Comment by arnohovhannisyan** [comment]
If anyone is still having trouble, I can send a PR that temporarily disables the use of fsevents on macOS until this issue is fixed.

**Comment by fillipvt** [comment]
Having the same issue. Pinpointed it the same way @wescoder did. Here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/16828078/55652072-22ba3500-57b0-11e9-8f21-bd88a6637c29.png)

**Comment by arnohovhannisyan** [comment]
I'm thinking this issue might be Mojave-specific as I didn't encounter this on High Sierra. I'll send a PR disabling the use of fsevents which will temporarily fix it.

**Comment by fillipvt** [comment]
That could also be a reason. I just recently upgraded to the 10.14.4 update. Although totally unsure on how to pin point the problem in that way.

**Comment by arnohovhannisyan** [comment]
If you know how to build the extension from source, you can try testing my new **experimental** [fix](https://github.com/arnohovhannisyan/code-settings-sync/tree/chokidar-fix) on Mojave.

**Comment by nekonenene** [comment]
@arnohovhannisyan
I tested `chokidar-fix` branch, but the error occured... 😢 

Visual Studio Code: 1.33.0
macOS: 10.14.4

<img width="823" alt="SC 666" src="https://user-images.githubusercontent.com/11713748/55672488-9191ae00-58d6-11e9-97d0-fbc3768000dd.png">

**Comment by arnohovhannisyan** [comment]
Ok, I guess we might have to find some other solution until this is fixed. Thanks for testing!

**Comment by arnohovhannisyan** [comment]
@nekonenene can you try clearing npm/yarn cache and then truing again without my fix? Fsevents was updated in v2.1.0 of chokidar, but maybe npm/yarn is using the old version from cache.

**Comment by nekonenene** [comment]
@arnohovhannisyan 

Thanks, I tried again. But, it still not works... The same error occurred.

commands:

```sh
rm -rf node_modules
npm cache clean --force
npm i
vsce package
code --install-extension code-settings-sync-3.2.8.vsix --force
```

**Comment by arnohovhannisyan** [comment]
@nekonenene What node version are you using?

**Comment by nekonenene** [comment]
@arnohovhannisyan 
Node.js v10.15.3.(latest LTS)
It occurs with also v8.15.1.

**Comment by arnohovhannisyan** [comment]
@nekonenene I think I may have found a solution. [https://github.com/ritwickdey/vscode-live-server/commit/ca594e49635f2ef6f921ff4dd99df1a275bb3d7d](https://github.com/ritwickdey/vscode-live-server/commit/ca594e49635f2ef6f921ff4dd99df1a275bb3d7d)

**Comment by arnohovhannisyan** [comment]
@nekonenene Can you test my newest changes to the [chokidar-fix](https://github.com/arnohovhannisyan/code-settings-sync/tree/chokidar-fix) branch?

**Comment by nekonenene** [comment]
Phew,,, I'm getting tired. 😷 

```sh
git pull
rm -rf package-lock.json yarn.lock node_modules
yarn
vsce package
code --install-extension code-settings-sync-3.2.8.vsix --force
```

And, I got the same error....
I would be grateful if you think much.

**Comment by arnohovhannisyan** [comment]
@nekonenene Sorry for wasting your time. Thank you for testing anyway!

**Comment by Spacebody** [comment]
I encountered the same issue. We encountered such a problem previously so quickly I disable this extension, and the problem is gone.

OS: Mojava 10.14.3
VS code: 1.33.0
Sync: 3.2.8

**Comment by arnohovhannisyan** [comment]
Everyone who's having this issue seems to be running Mojave. Is anyone having this issue in High Sierra or below?

**Comment by arnohovhannisyan** [comment]
Can anyone still having this issue try running this command and trying again?
```
npm un -g fsevents fs-extra
```

**Comment by wescoder** [comment]
I've already done this before and the problem persists, should I do it
again now?

My node version is 11.13.0

Em dom, 7 de abr de 2019 13:31, Arno Hovhannisyan <notifications@github.com>
escreveu:

**Comment by arnohovhannisyan** [comment]
@wescoder If you've already tried, then no.

**Comment by arnohovhannisyan** [comment]
@wescoder Can you try installing this version of the extension?

https://cdn.discordapp.com/attachments/549007146868539408/564493848777064462/code-settings-sync-3.2.8.vsix

**Comment by Spacebody** [comment]
@arnohovhannisyan Wow, it works on my computer.

OS: Mojava 10.14.3
VS code: 1.33.0

**Comment by arnohovhannisyan** [comment]
@Spacebody Thanks! After further testing, I'll send a PR with the updated changes.

**Comment by wescoder** [comment]
> @wescoder Can you try installing this version of the extension?
> 
> https://cdn.discordapp.com/attachments/549007146868539408/564493848777064462/code-settings-sync-3.2.8.vsix

@arnohovhannisyan It worked for me too! 🎉 😃 👍 🚀 :shipit: 

I'm glad we could help.

**Comment by arnohovhannisyan** [comment]
Just opened a new PR with the changes. I hope this gets merged soon!

**Comment by shanalikhan** [comment]
Sweet!
Thanks, I will release the new version in a few days.

**Comment by NayaStudio** [comment]
on High Sierra it works, on Mojave it run into problems as described above

**Comment by jamie1192** [comment]
@arnohovhannisyan yeah i'm gonna be *that* guy.. i'm on High Sierra having the same issue with VSCode 1.33 so it's not isolated to just Mojave..

**Comment by arnohovhannisyan** [comment]
Have you tried the fix I linked a few comments ago?

**Comment by jpgls** [comment]
Just to let you know - the fix in the version at: https://cdn.discordapp.com/attachments/549007146868539408/564493848777064462/code-settings-sync-3.2.8.vsix - works for me as well (woohoo) since I don't see anyone else with my system so far

macOS Sierra - 10.12.6
VSCode - 1.33.0
Node - 10.15.3

Thanks so much for the quick fix and the awesome extension!

**Comment by arnohovhannisyan** [comment]
@jpgls I'm glad it worked for you :). The fix should be merged into the official release in a few days.

**Comment by Spacebody** [comment]
You guys can temporally use the fixed version these days, and I hope the official release can use a new version number so that we can upgrade to the official version as usual.

**Comment by arnohovhannisyan** [comment]
@wescoder I know that this issue has been fixed already, but I was wondering if maybe you can test this version and see if it crashes. I want to find out which version of chokidar broke it on mac.
https://cdn.discordapp.com/attachments/549007146868539408/564953595892727853/code-settings-sync-3.2.8.vsix

**Comment by wescoder** [comment]
I'll take on this tomorrow and let you know if it works.

Em seg, 8 de abr de 2019 20:24, Arno Hovhannisyan <notifications@github.com>
escreveu:

**Comment by arnohovhannisyan** [comment]
Thanks!

**Comment by timgavin** [comment]
VSCode: 1.33.1
Mojave: 10.14.4
Settings Sync: 3.2.8

Still crashing :/

**Comment by arnohovhannisyan** [comment]
@timgavin Have you tried this?
https://cdn.discordapp.com/attachments/549007146868539408/564493848777064462/code-settings-sync-3.2.8.vsix

**Comment by timgavin** [comment]
@arnohovhannisyan I'm new to VSCode; what do I do with that?

**Comment by arnohovhannisyan** [comment]
@timgavin Go to the Extensions activity (the place where you install extensions), click the 3 dots on the top right, and click install vsix. Then choose the file I linked. This is a temporary solution until it is officially released.

**Comment by timgavin** [comment]
Tried it; still crashing.

![Screen Shot 2019-04-17 at 8 48 55 AM](https://user-images.githubusercontent.com/1012049/56301987-bfa09a80-60ed-11e9-9ee0-937ce3f7cebc.png)

**Comment by arnohovhannisyan** [comment]
@timgavin Try closing and reopening vscode. The message that the extension has been installed is still there, which means you haven't restarted vscode.

**Comment by timgavin** [comment]
I've restarted it a number of times (24 actually) while testing this and always receive that message if the extension is enabled. I installed the .vsix file, received that error message, restarted, and again received that error message.

I then disabled all extensions, restarted Code, enabled Settings Sync, received the error, restarted Code and received the error again. So, no extension conflict either.

**Comment by arnohovhannisyan** [comment]
@timgavin Can you post your console error log? You can get to it by going to Help -> Toggle Developer Tools on the menu bar.

**Comment by timgavin** [comment]
@arnohovhannisyan 

![Screen Shot 2019-04-17 at 9 04 08 AM](https://user-images.githubusercontent.com/1012049/56303005-dd6eff00-60ef-11e9-9ee2-626f12f26a72.png)

**Comment by arnohovhannisyan** [comment]
@timgavin That's weird. We've migrated away from fsevents on that version of the extension, so there shouldn't be any issues with fsevents.

Can you try running this?
```
npm un -g fsevents

Or

yarn global remove fsevents
```

**Comment by timgavin** [comment]
Ran `npm un -g fsevents`, restarted Code, problem persists.

Ran `yarn global remove fsevents` and received `-bash: yarn: command not found`

Uninstalled extension; restarted Code; reinstalled extension from file; restarted Code; error persists.

![Screen Shot 2019-04-17 at 9 13 19 AM](https://user-images.githubusercontent.com/1012049/56303617-2ecbbe00-60f1-11e9-9639-ade7edbd6c8e.png)

**Comment by wescoder** [comment]
@arnohovhannisyan Sorry for the late reply (I've been switching jobs this month).
My last attempt using https://cdn.discordapp.com/attachments/549007146868539408/564953595892727853/code-settings-sync-3.2.8.vsix was successfull and it works propperly.
If you want me to test other changes let me know.

**Comment by shanalikhan** [comment]
its fixed in `v3.2.9`
