### ISSUE TITLE
Sync : Error Logged In Console (Help menu > Toggle Developer Tools).

### ISSUE THREAD

**Issue by S1AnGeR** [shanalikhan/code-settings-sync#831]
🐛 **Describe the bug**  
clean install VS Code , install Sync Settings - try download settings from private gist:
Sync : Error Logged In Console (Help menu > Toggle Developer Tools).

🌴 **Visual Studio Code Version :** [ 1.33.0 ] 
🌴 **Code Settings Sync Version :** [ 3.2.8 ] 
🌴 **Standard or Insiders :** [ standart] 
🌴 **OSS or Portable :** [ OSS ] 
🌴 **Operating System :** [ Windows 10] 
🌴 **Occurs On:** [ Download ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ 098315d52e48044120f91c83375f9b0c ]

📰 **To Reproduce**
1. Go to 'CTRL+SHIFT+P'
2. Click on 'DOWNLOAD SETTINGS - gistID'
3. See error :
Sync : Error Logged In Console (Help menu > Toggle Developer Tools).

💪 **Expected behavior**
Downloading and sync settings

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode (Help Menu > Developer Tool - Console Tab). 
![image](https://user-images.githubusercontent.com/5192883/55666718-6ae26180-585b-11e9-8e26-9f955fcb701b.png)

**Comment by arnohovhannisyan** [comment]
Duplicate of #829

**Comment by arnohovhannisyan** [comment]
Resolved in #829, you can look there for the solution.

**Comment by arnohovhannisyan** [comment]
@S1AnGeR you might have entered an invalid gist id. Make sure it's correct and try again.

**Comment by devellopah** [comment]
upon fresh vscode installation, install extension, click on extension gear, choose _configure extension settings_ , feed id of valid gist to _gist id field_
and then _shift + ctrl + p_, _Sync: Download Settings_
![sync](https://user-images.githubusercontent.com/13398931/59252343-9b1bf700-8c34-11e9-8dc9-141436e2368d.png)

**Comment by objectbakery** [comment]
This issue still exists. Neither of the provided solutions works for me. This extensions is simply broken.

**Comment by benoitMariaux** [comment]
Yes, same for me @objectbakery

**Comment by nova76** [comment]
me too

**Comment by shanalikhan** [comment]
Guys check out the [troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) and see how the the different issues on how users were able to fix the thing.

You need to configure it correctly, documentation says it all.
But still you can perform different steps written over there to see how other people have fixed it.

I am always looking to improve the wiki and readme and help user configuring the Settings Sync.

**Comment by Nielson** [comment]
I ran into this error as well. I thought I got the correct Gist ID. Turned out I took the ID from where I created the token, and not from the Gist itself.

**Comment by edineu** [comment]
Hey guys,
Managed to get it working again, just had to update the Gist ID and  vooola.. it worked!

**Comment by blueray453** [comment]
When you download the settings, check output tab. In my case, it gave error and paused trying to download imagepreview & filewatcher extension.

I manually deleted them (the following lines) from the gist and the download completed.

 ```
{
    "metadata": {
      "id": "9240cee3-8289-4b9d-886e-531440411918",
      "publisherId": "buzzfrog.imagepreview",
      "publisherDisplayName": "buzzfrog"
    },
    "name": "imagepreview",
    "publisher": "buzzfrog",
    "version": "0.5.1"
  }
```
and
```
  {
    "metadata": {
      "id": "12e95fdd-b0d5-4978-8174-122b925efaf9",
      "publisherId": "AppulateInc.filewatcher",
      "publisherDisplayName": "AppulateInc"
    },
    "name": "filewatcher",
    "publisher": "AppulateInc",
    "version": "1.0.3"
  }
```
I know this is weird but it is what it is. I think someone from the dev-team (probably @shanalikhan) should look into it.

**Comment by ulises-castro** [comment]
For my case, I have to install "Visua Studio Code", because I had the open source version.
And when It was trying to fetch and install extensions these weren't available from Open Source Extensions...

After that, I don't face this problem anymore.

**Comment by aindriu80** [comment]
I think you have to set up VSCodium to work with extensions:
https://www.reddit.com/r/vscode/comments/hls9ef/vscodium_and_extensions/
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by redteg** [comment]
Sync error happening as the C Sharp extension names has change in my case:
Error: Error: Error: Extension 'ms-vscode.csharp' not found.	at c:\Users\username\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:22293

Info here about the extension name change:
https://alfredmyers.com/2020/03/06/idms-vscode-csharp-no-extensions-found/

Not sure how to "get out" of this loop

**Comment by samueleabs** [comment]
This helped me out in Linux.

https://stackoverflow.com/questions/64735558/sync-error-logged-in-console-help-menu-toggle-developer-tools

**Comment by yumeng-4213** [comment]
I face the same problem, sync block by installing a "extension", and I solved this issue by delete bad  "extension" via github.
follow this workflow:
github-> Your gists -> select gist I use to sync vscode -> Edit gist -> delete bad "extension" -> upload. done.
return to vscode download my setting.

**Comment by restuwahyu13** [comment]
install manual extension broken, if you installed using code sync stuck

**Comment by danieldanielecki** [comment]
Had the problem with `bracket-pair-colorizer`, which was removed from `VSCode`; had to edit my gist before syncing the settings and eventually fixing the issue.

**Comment by beetcb** [comment]
Try to `Sync: Reset Extension Settings`, which will clear all your local configurations related to Settings Sync.
And `SHIFT-ALT-D` -> re-login -> choose your gist -> issue solved. 
Hope that helps.

**Comment by MyCodeMyMoney** [comment]
> Had the problem with `bracket-pair-colorizer`, which was removed from `VSCode`; had to edit my gist before syncing the settings and eventually fixing the issue.

Me too, I hope the official can fix this bug！！！！！！

**Comment by andreyshirokoff** [comment]
> 

What kind the bad extension you say about? Setting Sync?

**Comment by ArtemArtemenkoArtem** [comment]
> Had the problem with `bracket-pair-colorizer`, which was removed from `VSCode`; had to edit my gist before syncing the settings and eventually fixing the issue.

Can you elaborate on how to get around this error?

**Comment by Lilkedus** [comment]
> 

Yes, this fixed it for me. Thank you!

**Comment by vstaskevicius** [comment]
> > Had the problem with `bracket-pair-colorizer`, which was removed from `VSCode`; had to edit my gist before syncing the settings and eventually fixing the issue.
> 
> Can you elaborate on how to get around this error?

Navigate to your gist and remove the **bracket-pair-colorizer** object.
<img width="538" alt="Screenshot 2022-07-28 at 12 21 43" src="https://user-images.githubusercontent.com/56963050/181470737-9c8713a1-eb4e-4665-96ee-5077d894bf2a.png">

The error occurs because the extension is deprecated. You may try installing [this one](https://marketplace.visualstudio.com/items?itemName=BracketPairColorDLW.bracket-pair-color-dlw) instead.
