### ISSUE TITLE
how to turn off notification of a new version?

### ISSUE THREAD

**Issue by raingart** [shanalikhan/code-settings-sync#959]
Quite often, when you turn on, a notification about a new minor version appears. It is so good that the extension is developing, but as an ordinary user it is not interesting for me to be on the pulse and so well working expansion.

I understand that this way you are trying to expand your active user base. But as for me it becomes annoying.

**Comment by wzdxy** [comment]
The `What's New in v3.4.0` page appeared  every time then I open a new window.
I had to watch it for a dozen times today ...

**Comment by shanalikhan** [comment]
>  appeared every time

@arnohovhannisyan can we configure it with configuration to hide the message even when not configured on startup

**Comment by arnohovhannisyan** [comment]
@shanalikhan Sure, we can use global state to hide it like the `Gist Newer` dialog.

**Comment by shanalikhan** [comment]
Yes, can you send PR. I will release v3.4.1 fixing it.

**Comment by shanalikhan** [comment]
It is fixed in `v3.4.1`. Let us know in case of query.

**Comment by raingart** [comment]
@shanalikhan thanks

**Comment by zhongdongy** [comment]
Hi team, I'm using `v3.4.3` on Visual Studio Code `v1.60.2` (Linux x64), but the "Welcome to Settings Sync" page keeps opening every time I open a new VSC window. I've already turned off "Show this page on startup" option, but it doesn't work. I'm thinking this is not a random case, because even I do a fresh install on macOS (Big Sur) and Windows 10/11, the issue still exists.

PS. I already checked that the plugin is configured and my settings are syncing.

**Comment by zhongdongy** [comment]
> Hi team, I'm using `v3.4.3` on Visual Studio Code `v1.60.2` (Linux x64), but the "Welcome to Settings Sync" page keeps opening every time I open a new VSC window. I've already turned off "Show this page on startup" option, but it doesn't work. I'm thinking this is not a random case, because even I do a fresh install on macOS (Big Sur) and Windows 10/11, the issue still exists.
> 
> PS. I already checked that the plugin is configured and my settings are syncing.

More info: VSC `1.60.2` was installed from flatpak, and after I uninstalled it then install official release `v1.61.0` from Microsoft website, the issue can be reproduced.
