### ISSUE TITLE
"Settings sync" screen appears

### ISSUE THREAD

**Issue by alkurop** [shanalikhan/code-settings-sync#963]
"Settings sync" screen appears on every time I start vscode.
I already removed your plugin but it still appears.
I hate it.
How do i get rid of it?
Very annoying

**Comment by arnohovhannisyan** [comment]
@alkurop Can you make sure that you've properly removed the extension? This can't happen if you did.

**Comment by jameswilliamiii** [comment]
I tried to uninstall it and the uninstall fails.  Same with disable. I ended up having to manually remove the extension.  On a mac you can run `rm -rf ~/.vscode/extensions/shan.code-settings-sync-3.4.0`.  Just make sure the version in the extension name matches what version is on your machine.

**Comment by bkbonner** [comment]
Yep, shows up every time I restart vscode.   :(

**Comment by NuroDev** [comment]
Is there no way to stop it from opening every time? I like Settings Sync and want to keep it but this screen opening every time I open VS Code is really irritating!

**Comment by shanalikhan** [comment]
Yes, we are planning to fix this issue in next version.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joecarney** [comment]
Same for me. Very annoying for an otherwise excellent extension. Would be better if you could release a hotfix for this instead of planning a fix in the next version 😉

**Comment by emezav** [comment]
Until it's fixed, you should try this dirty hack...

Open ~/.vscode/extensions/shan.code-settings-sync-3.4.0/out/extension.js. 

Search for:

OpenLandingPage=function()

It should look like this:

e.prototype.OpenLandingPage=function(){var e=this,t=this.webviews[0]

Add "return;" After the opening braces and before everything else:

e.prototype.OpenLandingPage=function(){return;var e=this,t=this.webviews[0]

This prevents the landing page from showing.

**Comment by k1nghat** [comment]
i have a different issue but even if i uninstall and also remove the extension from `~/.vscode/extensions/` when i install again, i dont get the regular setup procedure. is there some cache i dont know about?

**Comment by shanalikhan** [comment]
> Would be better if you could release a hotfix

We have found some other things to improve the Setup Guide and making the UX more better. Hold on we will release in next days. :)

thanks for patience, i'm getting alot of bad reviews and emails mentioning this thing only :smile:

**Comment by joecarney** [comment]
>  i'm getting alot of bad reviews and emails mentioning this thing only

I'm not surprised. 

This is why (if I were you) I'd release a hotfix to stop this bug and bad reviews happening, then make your improvements 😞

**Comment by shanalikhan** [comment]
>This is why (if I were you) I'd release a hotfix to stop this bug

There was a delay due to other issues during setup. We have improved the UX alot. It is fixed in `v3.4.1`. Let us know in case of query.

**Comment by dreznicek** [comment]
Upgraded to 3.4.1, yet still I get the `Settings Sync` screen.

**Comment by shanalikhan** [comment]
U can disable it using the checkbox in the bottom right corner

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joecarney** [comment]
Upgraded to v3.4.1, unchecked the checkbox bottom right still getting this welcome screen.  Am going to uninstall it 😞

**Comment by shanalikhan** [comment]
>  unchecked the checkbox bottom right still getting this welcome screen

have you reset the settings? after unchecking it.
It should not appear once you uncheck the checkbox until you reset the settings.

**Comment by joecarney** [comment]
This welcome screen is a really bad idea anyway, no idea why it should even be there. Extensions should be invisible in the background.  If I want to know more I can go to the extension and check out the home page

**Comment by joecarney** [comment]
I don't know what you mean by "reset the settings".  I unchecked the box, quit and opened again. Then checked it, quit and opened again, then unchecked it, quit and opened again.  No matter what I did it kept appearing.  I've removed it now.  May reinstall at a later date if I need to sync between machines.

**Comment by shanalikhan** [comment]
Okay, let me explain the steps.

1. Settings Sync UI will appear on startup automatically when you don't have Github token setup.
2. It will appear on upload/download when you have not configured Github token.
3. You can always disable the startup UI appearance while unchecking the `Don't Show at Startup` on the bottom right. It will disable startup appearance and will only show UI on upload/download ( when token not configured )
4. If you do the `Sync: Reset Extension Settings` it will reset the extension settings and will cause the UI to load once again on startup and you need to uncheck that box.


If you find other behaviour as intended, open issue for it, We will fix it.

**Comment by shanalikhan** [comment]
Duplicate of #959
